import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { slugifyChange, readLifecycleState, writeLifecycleState } from '../../lib/lifecycle.mjs';
import { tempDir, cleanup } from './helpers.mjs';
test('slugifyChange creates OpenSpec-safe change names',()=>assert.equal(slugifyChange(' Add Retry Policy! '),'add-retry-policy'));
test('slugifyChange returns empty slug when no safe characters remain',()=>assert.equal(slugifyChange('!!!'),''));
test('lifecycle state defaults to no active change',()=>{const d=tempDir();try{assert.deepEqual(readLifecycleState(d),{});}finally{cleanup(d);}});
test('lifecycle state round-trips',()=>{const d=tempDir();try{const s={change:'x',component:'api',phase:'spec',path:'openspec/changes/x'};writeLifecycleState(d,s);assert.deepEqual(readLifecycleState(d),s);assert.ok(fs.existsSync(path.join(d,'.truss/state.json')));}finally{cleanup(d);}});
